### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'includes')

### ISSUE THREAD

**Issue by iskrenpanteleev** [muxinc/upchunk#133]
Hello, the following error occurs when uploading files,

upchunk.ts:155 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'includes')
    at ye (upchunk.ts:155:42)
    at ve.sendChunkWithRetries (upchunk.ts:611:9)
    at async ve.sendChunks (upchunk.ts:643:9)

Th thing is that this issue does not happen when uploading files locally, it happens only on the production server.
The response code from the backend is 200 OK, no issues with it whatsoever.

**Comment by iskrenpanteleev** [comment]
Issue fixed after updating to the next version.
